#!/usr/bin/env python2.7

import argparse
import collections
import contextlib
import logging
import os
import re
import socket
import threading
import time
import urllib2
import urlparse

from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
from socket import AF_INET, SOCK_DGRAM
from SocketServer import ThreadingMixIn

import dns.resolver
import pyroute2.iproute
import systemd.daemon
import yaml

from pyroute2.netlink.rtnl.ifinfmsg import IFF_UP, IFF_RUNNING

__author__ = 'Aleksey Chudov <aleksey.chudov@gmail.com>'
__date__ = '14 Nov 2017'
__version__ = '1.0.6'


class AbstractCheck(threading.Thread):
    def __init__(self, name, status_message=False, interval=3, timeout=1):
        super(AbstractCheck, self).__init__(name=name)
        self.daemon = True
        self.status = Report.check_status(name)
        self.status_message = status_message
        self.interval = interval
        self.timeout = timeout

    def run(self):
        while self.is_alive():
            try:
                self.update_status()
            except Exception as e:
                logging.error('unexpected error: {}'.format(e))
                self.status.update(Status.ERROR)

            logging.debug(self.status)
            time.sleep(self.interval)

    def update_status(self):
        raise NotImplementedError


class CheckDefaultRoutes(AbstractCheck):
    def update_status(self):
        status = Status.OK
        with pyroute2.iproute.IPRoute() as ip:
            ip.get_timeout = self.timeout
            if not ip.get_default_routes():
                logging.error('no default route')
                status = Status.ERROR

        self.status.update(status)


class CheckDNS(AbstractCheck):
    def __init__(self, host, qname, qtype='A', port=53, tcp=False, **kwargs):
        super(CheckDNS, self).__init__(**kwargs)
        self.resolver = dns.resolver.Resolver(configure=False)
        self.resolver.nameservers.append(host)
        self.resolver.port = port
        self.resolver.lifetime = self.timeout
        self.qname = qname
        self.qtype = qtype
        self.tcp = tcp

    def update_status(self):
        status = Status.OK
        try:
            self.resolver.query(self.qname, self.qtype, tcp=self.tcp)
        except dns.exception.DNSException as e:
            logging.error("DNS query '{} {}' to {}:{} failed: {}".format(
                self.qname, self.qtype, self.resolver.nameservers[0],
                self.resolver.port, e))
            status = Status.ERROR

        self.status.update(status)


class CheckInterfaces(AbstractCheck):
    def __init__(self, interfaces, **kwargs):
        super(CheckInterfaces, self).__init__(**kwargs)
        self.interfaces = interfaces

    @staticmethod
    def interfaces_info(timeout):
        if_names = {}
        if_indices = {}

        with pyroute2.iproute.IPRoute() as ip:
            ip.get_timeout = timeout

            for msg in ip.link('dump'):
                index = msg['index']
                flags = msg['flags']
                name = msg.get_attr('IFLA_IFNAME')
                if_names[name] = {'index': index, 'flags': flags, 'address': []}
                if_indices[index] = if_names[name]

            for msg in ip.get_addr():
                index = msg['index']
                address = msg.get_attr('IFA_ADDRESS')
                if_indices[index]['address'].append(address)

        return if_names

    def update_status(self):
        status = Status.OK
        interfaces_info = self.interfaces_info(self.timeout)

        for name in self.interfaces:
            if name not in interfaces_info:
                logging.error("interface '{}' does not exist".format(name))
                status = Status.ERROR

            elif not interfaces_info[name]['flags'] & (IFF_UP | IFF_RUNNING):
                logging.error("interface '{}' is not UP".format(name))
                status = Status.ERROR

            elif not interfaces_info[name]['address']:
                logging.error("interface '{}' address not set".format(name))
                status = Status.ERROR

        self.status.update(status)


class CheckSysctl(AbstractCheck):
    def __init__(self, variables, **kwargs):
        super(CheckSysctl, self).__init__(**kwargs)
        self.variables = variables

    @staticmethod
    def sysctl_read(variable):
        sysctl_path = '/proc/sys/' + '/'.join(variable.split('.'))
        sysctl_value = ''
        try:
            with open(sysctl_path) as sysctl_file:
                sysctl_value = sysctl_file.read().strip()
        except IOError as e:
            logging.debug('error reading {}: {}'.format(variable, e))

        return sysctl_value

    def update_status(self):
        status = Status.OK
        for variable, value in self.variables.items():
            sysctl_value = self.sysctl_read(variable)
            if sysctl_value != str(value):
                logging.error("{} value is '{}' not '{}'".format(
                    variable, sysctl_value, value))
                status = Status.ERROR

        self.status.update(status)


class CheckTCP(AbstractCheck):
    def __init__(self, host, port, **kwargs):
        super(CheckTCP, self).__init__(**kwargs)
        self.host = host
        self.port = port

    def update_status(self):
        status = Status.OK
        try:
            socket.create_connection(
                (self.host, self.port), self.timeout).close()
        except socket.error as e:
            logging.error('connection to {}:{} failed: {}'.format(
                self.host, self.port, e))
            status = Status.ERROR

        self.status.update(status)


class CheckUDPRequest(AbstractCheck):
    def __init__(self, host, port, request, response,
                 max_response_size=1024, **kwargs):
        super(CheckUDPRequest, self).__init__(**kwargs)
        self.host = host
        self.port = port
        self.request = request
        self.response = response
        self.max_response_size = max_response_size

    def update_status(self):
        status = Status.OK
        message = ''
        try:
            with contextlib.closing(socket.socket(AF_INET, SOCK_DGRAM)) as sock:
                sock.settimeout(self.timeout)
                sock.connect((self.host, self.port))
                sock.send(self.request)
                response = sock.recv(self.max_response_size).rstrip()
                if re.match(self.response, response):
                    if self.status_message:
                        message = response
                else:
                    logging.error("{}:{} response is '{}' not '{}'".format(
                        self.host, self.port, response, self.response))
                    status = Status.ERROR

        except socket.error as e:
            logging.error('request to {}:{} failed: {}'.format(
                self.host, self.port, e))
            status = Status.ERROR

        self.status.update(status, message)


class CheckURL(AbstractCheck):
    def __init__(self, url, response, **kwargs):
        super(CheckURL, self).__init__(**kwargs)
        self.url = url
        self.response = response

    def update_status(self):
        status = Status.OK
        message = ''
        try:
            r = urllib2.urlopen(self.url, timeout=self.timeout)
            response = r.read().strip()
            if re.match(self.response, response):
                if self.status_message:
                    message = response
            else:
                logging.error("{} response is '{}' not '{}'".format(
                    self.url, response, self.response))
                status = Status.ERROR

        except (socket.error, urllib2.URLError) as e:
            logging.error('{} {}'.format(self.url, e))
            status = Status.ERROR

        self.status.update(status, message)


class CheckQuery(object):
    def __init__(self, checks, query, config):
        self.checks = checks
        self.query = query
        self.config = config
        self.status = Report.query_status(self.query)

    def check_virtual_interface(self):
        name = self.checks.get('virtual_if')
        addresses = self.checks.get('virtual_ip')
        if not name and addresses or name and not addresses:
            logging.error(
                "both 'virtual_if' and 'virtual_ip' parameters are required")
            return Status.ERROR

        status = Status.OK
        interfaces_info = CheckInterfaces.interfaces_info(
            self.config.query_timeout)

        if name not in interfaces_info:
            logging.error("interface '{}' does not exist".format(name))
            status = Status.ERROR

        elif not interfaces_info[name]['flags'] & (IFF_UP | IFF_RUNNING):
            logging.error("interface '{}' is not UP".format(name))
            status = Status.ERROR

        elif (CheckSysctl.sysctl_read(
                'net.ipv4.conf.{}.rp_filter'.format(name)) != '0'):
            logging.error("interface '{}' rp_filter not disabled".format(name))
            status = Status.ERROR
        else:
            for address in addresses.split(','):
                if address not in interfaces_info[name]['address']:
                    logging.error("interface '{}' address '{}' not set".format(
                        name, address))
                    status = Status.ERROR

        return status

    def query_status(self):
        status = Status.OK
        for check in self.checks:
            if check in ('exclude', 'virtual_ip'):
                continue

            if check == 'virtual_if':
                status = self.check_virtual_interface()
            else:
                logging.error("invalid check '{}'".format(check))
                status = Status.ERROR

        return status

    def update_status(self):
        if not self.status.is_expired(self.config.query_cache_ttl):
            logging.debug('cached {}'.format(self.status))
            return

        try:
            self.status.update(self.query_status())
        except Exception as e:
            logging.error('unexpected error: {}'.format(e))
            self.status.update(Status.ERROR)

        logging.debug('updated {}'.format(self.status))


class HTTPRequestHandler(BaseHTTPRequestHandler, object):
    protocol_version = 'HTTP/1.1'
    server_version = 'RSCheck/' + __version__
    rbufsize = -1
    wbufsize = -1

    def __init__(self, *args):
        self.location = None
        self.query = None
        self.checks = {}
        super(HTTPRequestHandler, self).__init__(*args)

    def do_GET(self):
        self.handle_request()

    def do_HEAD(self):
        self.handle_request()

    def checks_exclude(self):
        if 'exclude' in self.checks:
            return self.checks['exclude'].split(',')
        else:
            return ()

    def handle_request(self):
        self.location, self.query = urlparse.urlsplit(self.path)[2:4]

        if self.location != self.server.config.location:
            logging.error("invalid location '{}'".format(self.location))
            self.send_error(404)

        elif self.query and not self.check_query():
            logging.error("invalid query '{}'".format(self.query))
            self.send_error(400)

        elif self.command == 'GET':
            message = Report.message(self.query, self.checks_exclude())
            logging.debug("message='{}'".format(message))
            self.send_response(200)
            self.send_header('Content-Type', 'text/html; charset=utf-8')
            if self.server.config.keep_alive:
                self.send_header('Content-Length', len(message))
            else:
                self.send_header('Connection', 'close')
            self.end_headers()
            self.wfile.write(message)

        elif self.command == 'HEAD':
            if Report.is_ok(self.query, self.checks_exclude()):
                self.send_response(200)
            else:
                self.send_response(503)
            if self.server.config.keep_alive:
                self.send_header('Content-Length', 0)
            else:
                self.send_header('Connection', 'close')
            self.end_headers()

    def check_query(self):
        for check in urlparse.unquote(self.query).split('&'):
            check_args = check.split('=')
            if len(check_args) != 2:
                return False
            self.checks[check_args[0]] = check_args[1]

        CheckQuery(self.checks, self.query, self.server.config).update_status()
        return True


class Config(argparse.Namespace):
    def __getattr__(self, name):
        return self.__dict__[name]


class ThreadingHTTPServer(ThreadingMixIn, HTTPServer):
    pass


class HTTPServerThread(threading.Thread):
    def __init__(self, name, address, port, location, keep_alive=True,
                 request_timeout=3, query_cache_ttl=5, query_timeout=1,
                 wait_status_interval=3, wait_status_timeout=0):
        super(HTTPServerThread, self).__init__(name=name)
        self.daemon = True
        self.address = address
        self.port = port
        self.request_timeout = request_timeout
        self.wait_status_interval = wait_status_interval
        self.wait_status_timeout = wait_status_timeout
        self.config = Config(
            location=location, keep_alive=keep_alive,
            query_cache_ttl=query_cache_ttl, query_timeout=query_timeout)

    def run(self):
        HTTPRequestHandler.timeout = self.request_timeout
        server_address = (self.address, self.port)
        server = ThreadingHTTPServer(
            server_address, HTTPRequestHandler, bind_and_activate=False)
        server.config = self.config
        server.daemon_threads = self.daemon
        server.server_bind()

        while self.wait_status_timeout > 0:
            logging.info('waiting {}s or success status to start'.format(
                self.wait_status_timeout))
            time.sleep(self.wait_status_interval)
            self.wait_status_timeout -= self.wait_status_interval
            if Report.is_ok():
                break

        server.server_activate()
        logging.info('listening on {}:{}'.format(*server_address))
        server.serve_forever()


class MaintenanceThread(AbstractCheck):
    def update_status(self):
        Report.clean_query_cache()
        self.status.update(Status.OK)


class Status(object):
    OK = 0
    ERROR = 1

    def __init__(self, error=OK, message=''):
        self.error = error
        self.message = message
        self.timestamp = 0

    def __str__(self):
        return "{}(error={}, message='{}', timestamp={})".format(
            self.__class__.__name__, self.error, self.message, self.timestamp)

    def is_expired(self, ttl):
        return time.time() - self.timestamp > ttl

    def update(self, error, message=''):
        self.error = error
        self.message = message
        self.timestamp = time.time()


class Report(object):
    default_message = {Status.OK: 'true', Status.ERROR: 'false'}
    check_cache = collections.defaultdict(Status)
    query_cache = collections.defaultdict(Status)
    query_cache_ttl = 60

    @classmethod
    def clean_query_cache(cls):
        logging.debug('query cache size: {}'.format(len(cls.query_cache)))
        for query in list(cls.query_cache):
            if cls.query_cache[query].is_expired(cls.query_cache_ttl):
                logging.debug("query cache expired: '{}'".format(query))
                del cls.query_cache[query]

    @classmethod
    def check_status(cls, name):
        return cls.check_cache[name]

    @classmethod
    def query_status(cls, name):
        return cls.query_cache[name]

    @classmethod
    def is_ok(cls, query='', exclude=()):
        return cls.is_query_ok(query) and cls.is_check_ok(exclude)

    @classmethod
    def is_check_ok(cls, exclude):
        return not any(cls.check_cache[name].error
                       for name in cls.check_cache.viewkeys() - exclude)

    @classmethod
    def is_query_ok(cls, query):
        return not (query in cls.query_cache and cls.query_cache[query].error)

    @classmethod
    def message(cls, query='', exclude=()):
        status = Status.OK if cls.is_query_ok(query) else Status.ERROR
        messages = collections.defaultdict(list)

        for name in cls.check_cache.viewkeys() - exclude:
            if cls.check_cache[name].message:
                messages[cls.check_cache[name].error].append(
                    cls.check_cache[name].message)

            if cls.check_cache[name].error:
                status = Status.ERROR

        if status in messages:
            return '; '.join(messages[status])
        else:
            return cls.default_message[status]


class SystemService(object):
    def __init__(self, threads):
        self.threads = threads
        self.interval = self.watchdog_interval()

    def is_alive(self):
        return all(thread.is_alive() for thread in self.threads)

    @staticmethod
    def watchdog_interval(default_usec=3000000):
        return int(os.environ.get('WATCHDOG_USEC', default_usec)) / 1000000 / 2

    def start(self):
        for thread in self.threads:
            logging.debug('starting {}'.format(thread))
            thread.start()

        systemd.daemon.notify('READY=1')

        while self.is_alive():
            systemd.daemon.notify('WATCHDOG=1\nSTATUS=Threads: {}'.format(
                threading.active_count()))
            time.sleep(self.interval)

        logging.debug('system service finished')


class RSCheck(object):
    @staticmethod
    def main():
        parser = argparse.ArgumentParser()
        parser.add_argument('config_file')
        with open(parser.parse_args().config_file) as config_file:
            config = Config(**yaml.load(config_file))

        logging.basicConfig(
            format=config.logging['format'],
            level=logging.getLevelName(config.logging['level']))
        logging.debug('config: {}'.format(config))

        threads = []
        for thread in config.threads:
            thread_config = config.threads[thread]
            thread_class = globals()[thread_config.pop('class')]
            threads.append(thread_class(name=thread, **thread_config))

        SystemService(threads).start()


if __name__ == '__main__':
    RSCheck.main()
